name: travelmate
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  sizer: ^2.0.15
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  supabase_flutter: ^2.5.6
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  image_picker: ^1.1.2
  web: any
  flutter_local_notifications: ^19.3.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  google_sign_in: ^7.1.0
  firebase_storage: ^12.4.8
  google_maps_flutter: ^2.12.3
  intl: ^0.20.2
  geolocator: ^14.0.2
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  shimmer: ^3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/